# Generated by Django 3.0.7 on 2020-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200605_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_no',
            field=models.CharField(default='*', max_length=30),
        ),
    ]
