# Generated by Django 3.0.7 on 2020-06-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='orders'),
        ),
    ]
