# Generated by Django 3.0.7 on 2020-06-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
