# Generated by Django 3.0.7 on 2020-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='image',
            new_name='attach_file',
        ),
    ]
