# Generated by Django 3.0.7 on 2020-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200609_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'done'), ('-1', 'unsuccess')], default=0, max_length=10),
        ),
    ]
