# Generated by Django 3.0.7 on 2020-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200609_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
