# Generated by Django 3.0.7 on 2020-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200609_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'waiting for payment'), ('1', 'pending'), ('2', 'done'), ('-1', 'unsuccess payment')], default='0', max_length=10),
        ),
    ]
